### ISSUE TITLE
PyPI tarball is missing some of test suite files

### ISSUE THREAD

**Issue by mgorny** [lorien/test_server#21]
The release tarball has only the following files from `test` directory:

```
test-server-0.0.31/test/
test-server-0.0.31/test/server.py
test-server-0.0.31/test/__init__.py
```

This is apparently insufficient to run the test suite.

**Comment by jayvdb** [comment]
`MANIFEST.in` contains `recursive_include test *.py` , which may have worked at some point, but doesnt work now.

The underscore needs to be a hyphen.
