### ISSUE TITLE
 Importing ABC directly from collections module was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [lorien/test_server#23]
https://bugzilla.redhat.com/show_bug.cgi?id=1793021

https://github.com/lorien/test_server/blob/e46b5f4c0b38b9c98d90625407c91855f725ed5a/test_server/server.py#L9

Thanks for the library!

**Comment by rapgro** [comment]
Does this work instead?
```
import collections.defaultdict
import collections.Iterable
```

**Comment by tirkarthi** [comment]
The project also supports Python 2. So something like below would be better compatible.

```python
try:
    # For Python 3.3+
    from collections.abc import Iterable
except ImportError:
    # For Python 2
    from collections import Iterable
```

**Comment by rapgro** [comment]
OK, thanks. Could you file this patch as a pull request?

**Comment by tirkarthi** [comment]
Thanks, raised https://github.com/lorien/test_server/pull/24.

**Comment by rapgro** [comment]
ping

**Comment by lorien** [comment]
Fixed.
